version: '3.7'

services:
  e-ticket-front:
    container_name: e-ticket-front
    build:
      context: e-ticket-front
      dockerfile: Dockerfile
    volumes:
      - ./e-ticket-front:/front
    ports:
      - "3010:3000"

  api-gateway:
    user: node
    build:
      context: api-gateway
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/home/node
    command: sh -c "npm install && npm run start:dev"

  auth-back:
    user: node
    build:
      context: auth-back
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./auth-back:/home/node
    command: sh -c "npm install && npm run start:dev"

  auth-mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
