version: '3.7'

services:
  e-ticket-front:
    container_name: e-ticket-front
    build:
      context: e-ticket-front
      dockerfile: Dockerfile
    volumes:
      - ./e-ticket-front:/front
    ports:
      - "3010:3000"

  auth:
    build:
      context: ./e-ticket-back
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./e-ticket-back/apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - ./e-ticket-back:/usr/src/app

  gateway:
    build:
      context: ./e-ticket-back
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    ports:
      - "3003:3003"
    volumes:
      - ./e-ticket-back:/usr/src/app

  company:
    build:
      context: ./e-ticket-back
      dockerfile: ./apps/company/Dockerfile
      target: development
    command: pnpm run start:dev company
    ports:
      - "3004:3004"
    volumes:
      - ./e-ticket-back:/usr/src/app

  products:
    build:
      context: ./e-ticket-back
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: pnpm run start:dev products
    ports:
      - "3005:3005"
    volumes:
      - ./e-ticket-back:/usr/src/app

  ticket:
    build:
      context: ./e-ticket-back
      dockerfile: ./apps/ticket/Dockerfile
      target: development
    command: pnpm run start:dev ticket
    ports:
      - "3006:3006"
    volumes:
      - ./e-ticket-back:/usr/src/app

  fidelity:
    build:
      context: ./e-ticket-back
      dockerfile: ./apps/fidelity/Dockerfile
      target: development
    command: pnpm run start:dev fidelity
    ports:
      - "3007:3007"
    volumes:
      - ./e-ticket-back:/usr/src/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
