import { test, expect } from '@playwright/test';

test('Gen ticket', async ({ page }) => {
  await page.goto('http://localhost:3010/');
  await page.getByRole('button', { name: 'Connexion' }).click();
  await page.getByPlaceholder('john.doe@gmail.com').click();
  await page.getByPlaceholder('john.doe@gmail.com').fill('odessaentreprise@gmail.com');
  await page.getByPlaceholder('john.doe@gmail.com').press('Tab');
  await page.getByLabel('Mot de passe').fill('Odessa0.');
  await page.getByRole('button', { name: 'Connexion' }).click();
  await page.getByRole('button', { name: 'Application' }).click();
  await page.locator('button').nth(3).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'Ajouter un produit' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByLabel('Nom du produit').click();
  await page.getByLabel('Nom du produit').fill('Café');
  await page.getByLabel('Prix du produit (en €)').click();
  await page.getByLabel('Prix du produit (en €)').fill('3');
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'Ajouter un produit' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByLabel('Nom du produit').click();
  await page.getByLabel('Nom du produit').fill('Thé');
  await page.getByLabel('Prix du produit (en €)').click();
  await page.getByLabel('Prix du produit (en €)').fill('2');
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'Nouvelle commande' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Nouveau produit ​' }).click();
  await page.getByRole('option', { name: 'Café' }).click();
  await page.locator('button').nth(1).click();
  await page.getByRole('button', { name: 'Nouveau produit Café' }).click();
  await page.getByRole('option', { name: 'Thé' }).click();
  await page.getByLabel('Renseigner le mail').click();
  await page.getByLabel('Renseigner le mail').click();
  await page.getByRole('button', { name: 'Finaliser la commande' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'Nouvelle commande' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Nouveau produit ​' }).click();
  await page.getByRole('option', { name: 'Café' }).click();
  await page.getByRole('button', { name: 'Nouveau produit Café' }).click();
  await page.locator('#menu- div').first().click();
  await page.getByRole('button', { name: 'Nouveau produit Café' }).click();
  await page.getByRole('option', { name: 'Thé' }).click();
  await page.locator('button').nth(1).click();
  await page.getByRole('button', { name: 'Finaliser la commande' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.getByRole('button', { name: 'Mon entreprise' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Afficher le QR Code' }).click();
  await page1.locator('body').click();
});