name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull images
        run: docker compose pull --ignore-pull-failures || true
      - name: Start services
        run: docker compose up --build -d
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./e-ticket-front
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:e-ticket-front"
          push: true
          tags: matthieucmp/e-ticket:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/html/
            if [ ! -d e-ticket ]; then
              git clone git@github.com:challenge-s2/e-ticket.git
              cd e-ticket/e-ticket-back/apps/auth
              echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
              echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
              echo "HTTP_PORT=3001" >> .env
              echo "TCP_PORT=3002" >> .env
              cd /var/www/html/
            fi
            cd e-ticket
            git pull
            git status
            cd e-ticket-back
            pnpm i
            cd ..
            docker compose run -t e-ticket-front npm i
            docker compose up -d --build
